import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:aging_in_place/models/assessment_model.dart';
import 'package:intl/intl.dart';

class ReportService {
  static Future<Uint8List> generateMedicalReport(
    AssessmentModel assessment,
    List<AssessmentModel> history,
  ) async {
    final pdf = pw.Document();
    final name = assessment.metadata.subjectName ?? 'Senior';
    final date = DateFormat.yMMMd().format(assessment.metadata.createdAt);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Aging In Place - Medical Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(date),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            
            // 1. Demographics
            pw.Text('Senior Profile', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            pw.Bullet(text: 'Name: $name'),
            pw.Bullet(text: 'Age: ${assessment.metadata.subjectAge ?? 'N/A'}'),
            pw.Bullet(text: 'Gender: ${assessment.metadata.subjectGender ?? 'N/A'}'),
            pw.Bullet(text: 'Living Situation: ${assessment.metadata.livingSituation ?? 'N/A'}'),
            pw.SizedBox(height: 20),

            // 2. Current Score
            pw.Text('Current AIP Assessment', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _buildScoreBox('AIP Score', assessment.calculatedResults.scoreFinalAip),
                _buildScoreBox('Health', assessment.calculatedResults.scoreFwb),
                _buildScoreBox('Care Team', assessment.calculatedResults.scoreCt),
                _buildScoreBox('Home Safety', assessment.calculatedResults.scoreEs),
              ],
            ),
            pw.SizedBox(height: 20),

            // 3. Score History
            pw.Text('Recent Score History', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            pw.TableHelper.fromTextArray(
              headers: ['Date', 'AIP Score', 'Health', 'Team', 'Home'],
              data: history.take(10).map((a) => [
                DateFormat.yMd().format(a.metadata.createdAt),
                a.calculatedResults.scoreFinalAip.toInt().toString(),
                a.calculatedResults.scoreFwb.toInt().toString(),
                a.calculatedResults.scoreCt.toInt().toString(),
                a.calculatedResults.scoreEs.toInt().toString(),
              ]).toList(),
            ),
            pw.SizedBox(height: 20),

            // 4. Disclaimer
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 40),
              child: pw.Text(
                'DISCLAIMER: This report is generated by ALBERTai and is intended for informational purposes only. It is not a clinical diagnosis. Please consult with a licensed medical professional for formal medical advice.',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700, fontStyle: pw.FontStyle.italic),
              ),
            ),
          ];
        },
      ),
    );

    return await pdf.save();
  }

  static pw.Widget _buildScoreBox(String label, double score) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
      ),
      child: pw.Column(
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 10)),
          pw.Text(score.toInt().toString(), style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
