// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZckZhMbe1oT9rYfug3b44tkdjsNiSqk', 
    appId: '1:344008984280:web:fb2b44e420f3b93c2079ad',
    messagingSenderId: '344008984280',
    projectId: 'aginginplace-mvp',
    authDomain: 'aginginplace-mvp.firebaseapp.com',
    storageBucket: 'aginginplace-mvp.firebasestorage.app',
    measurementId: 'G-JHWTCMHT4K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_2eH0JyN8XlsU0QsLy3uc64QC6WfYwmg',
    appId: '1:344008984280:ios:c6de76fbdb09d4532079ad',
    messagingSenderId: '344008984280',
    projectId: 'aginginplace-mvp',
    storageBucket: 'aginginplace-mvp.firebasestorage.app',
    iosBundleId: 'com.example.agingInPlace',
  );
  
  static const FirebaseOptions macos = ios; 
}
